use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir);

    let logo_src = Path::new("logos");
    let logo_dst = out_path.join("logos");

    fs::create_dir_all(&logo_dst).unwrap();

    let mut entries: Vec<String> = fs::read_dir(logo_src)
        .unwrap()
        .flatten()
        .filter(|e| e.file_type().map(|t| t.is_file()).unwrap_or(false))
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    entries.sort();

    for name in &entries {
        let src = Path::new("logos").join(name);
        let dst = logo_dst.join(name);
        fs::copy(&src, &dst).unwrap();
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n");
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub fn embedded_keys() -> &'static [&'static str] {\n");
    code.push_str("    &[\n");
    for name in &entries {
        code.push_str(&format!("        \"{}\",\n", name));
    }
    code.push_str("    ]\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub fn get_embedded(key: &str) -> Option<&'static str> {\n");
    code.push_str("    match key {\n");
    for name in &entries {
        code.push_str(&format!(
            "        \"{}\" => Some(include_str!(\"logos/{}\")),\n",
            name, name
        ));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let dest_path = out_path.join("logos_generated.rs");
    fs::write(&dest_path, code).unwrap();

    println!("cargo:rerun-if-changed=logos");
}
