#!/usr/bin/env python3
"""atlasfetch — fetch customizável com ASCII centralizada e painéis powerline"""

import os, sys, json, shutil, re, subprocess

# ═══════════════════════════════════════════════════════════
# Logo embutido (AtlasWM)
# ═══════════════════════════════════════════════════════════
ATLAS_LOGO = (
    "                    -`\n"
    "                   .o+`\n"
    "                  `ooo/\n"
    "                 `+oooo:\n"
    "                `+oooooo:\n"
    "                -+oooooo+:\n"
    "              `/:-:++oooo+:\n"
    "             `/++++/+++++++:\n"
    "            `/++++++++++++++:\n"
    "           `/+++ooooooooooooo/`\n"
    "          ./ooosssso++osssssso+`\n"
    "         .oossssso-````/ossssss+`\n"
    "        -osssssso.      :ssssssso.\n"
    "       :osssssss/        osssso+++.\n"
    "      /ossssssss/        +ssssooo/-\n"
    "    `/ossssso+/:-        -:/+osssso+-\n"
    "   `+sso+:-`                 `.-/+oso:\n"
    "  `++:.                           `-/+/\n"
    " .`                                 `/\n"
)

# ═══════════════════════════════════════════════════════════
# Logos por distribuição (neofetch official)
# ═══════════════════════════════════════════════════════════
DISTRO_LOGOS = {
  "arch": "                    -`\n                   .o+`\n                  `ooo/\n                 `+oooo:\n                `+oooooo:\n                -+oooooo+:\n              `/:-:++oooo+:\n             `/++++/+++++++:\n            `/++++++++++++++:\n           `/+++ooooooooooooo/`\n          ./ooosssso++osssssso+`\n         .oossssso-````/ossssss+`\n        -osssssso.      :ssssssso.\n       :osssssss/        osssso+++.\n      /ossssssss/        +ssssooo/-\n    `/ossssso+/:-        -:/+osssso+-\n   `+sso+:-`                 `.-/+oso:\n  `++:.                           `-/+/\n .`                                 `/\n",
  "nixos": "          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖\n          ▜███▙       ▜███▙  ▟███▛\n           ▜███▙       ▜███▙▟███▛\n            ▜███▙       ▜██████▛\n     ▟█████████████████▙ ▜████▛     ▟▙\n    ▟███████████████████▙ ▜███▙    ▟██▙\n           ▄▄▄▄▖           ▜███▙  ▟███▛\n          ▟███▛             ▜██▛ ▟███▛\n         ▟███▛               ▜▛ ▟███▛\n▟███████████▛                  ▟██████████▙\n▜██████████▛                  ▟███████████▛\n      ▟███▛ ▟▙               ▟███▛\n     ▟███▛ ▟██▙             ▟███▛\n    ▟███▛  ▜███▙           ▝▀▀▀▀\n    ▜██▛    ▜███▙ ▜██████████████████▛\n     ▜▛     ▟████▙ ▜████████████████▛\n           ▟██████▙       ▜███▙\n          ▟███▛▜███▙       ▜███▙\n         ▟███▛  ▜███▙       ▜███▙\n         ▝▀▀▀    ▀▀▀▘       ▀▀▀▘\n",
  "ubuntu": "            .-/+oossssoo+\\-.\n         `:+ssssssssssssssssss+:`\n       -+ssssssssssssssssssyyssss+-\n     .ossssssssssssssssssdMMMNysssso.\n    /ssssssssssshdmmNNmmyNMMMMhssssss\\\n   +ssssssssshmydMMMMMMMNddddy:ssssssss+\n  /sssssssshNMMMyhyyyyhmNMMMNhsssssssss\\\n .ssssssssdMMMNhsssssssssshNMMMdssssssss.\n+sssshhhyNMMNyssssssssssssyNMMMyssssssss+\nossyNMMMNyMMhssssssssssssssshmmmhssssssso\nossyNMMMNyMMhsssssssssssssshmmmhssssssso\n+sssshhhyNMMNyssssssssssssyNMMMyssssssss+\n.ssssssssdMMMNhsssssssssshNMMMdssssssss.\n \\sssssssshNMMMyhyyyyhdNMMMNhsssssssss/\n   +sssssssssdmmydMMMMMMMMddddy:ssssssss+\n    \\ssssssssssshdmNNNNmyNMMMMhssssssss/\n     .ossssssssssssssssssdMMMNyssssso.\n       -+sssssssssssssssssyyyssss+-\n         `:+ssssssssssssssssss+:`\n             .-\\+oossssoo+\\-.\n",
  "fedora": "             .',;::::;,'.\n          .';:cccccccccccc:;,.\n       .;cccccccccccccccccccccc;.\n     .:cccccccccccccccccccccccccc:.\n   .;ccccccccccccc;.:dddl:.;ccccccc;.\n  .:ccccccccccccc;OWMKOOXMWd;ccccccc:.\n .:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.\n,cccccccccccccc;MMM.;cc;;WW:;cccccccc,\n:cccccccccccccc;MMM.;cccccccccccccccc:\n:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:\ncccccc;0MMKxdd:;MMMkddc.;cccccccccccc;\ncccc;XM0';cccc;MMM.;cccccccccccccccc'\ncccc;MMo;ccccc;MMW.;ccccccccccccccc;\ncccc;0MNc.ccc.xMMd;ccccccccccccccc;\ncccccc;dNMWXXXWM0:;cccccccccccccc:,\ncccccccc;.:odl:.;cccccccccccccc:,.\n.:cccccccccccccccccccccccccccc:'.\n  '::cccccccccccccc::;,.\n",
  "void": "                __.;=====;.__\n             _.=+==++=++=+=+===;.\n              -=+++=+===+=+=+++++=_\n         .     -=:     `--==+=++==.\n        _vi,    `            --+=++++:\n       .uvnvi.       _._       -==+==+.\n      .vvnvnI`    .;==|==;.     :|=||=|.\n+QmQQmpvvnv; _yYsyQQWUUQQQm #QmQ#:QQQWUV$QQm.\n -QQWQWpvvo wZ?.wQQQE==<QWWQ/QWQW.QQWW(: jQWQE\n  -$QQQQmmU'  jQQQ@+=<QWQQ)mQQQ.mQQQC+;jWQQ@'\n   -$WQ8YnI:   QWQQwgQQWV`mWQQ.jQWQQgyyWW@!\n     -1vvnvv.     ~+++`        ++|+++\n       +vnvnnv,                 `-|===\n        +vnvnvns.           .      :=-\n         -Invnvvnsi..___..=sv=.     `\n           +Invnvnvnnnnnnnnvvnn;.\n             ~|Invnvnvvnvvvnnv}+`\n                -~|{*l}*|~\n",
  "debian": "       _,met$$$$$gg.\n     ,g$$$$$$$$$$$$$$$P.\n   ,g$$P\"        \"\"\"Y$$.\".\n  ,$$P'              `$$$.\n ',$$P       ,ggs.     `$$b:\n `d$$'     ,$P\"'   .    $$$\n  $$P      d$'     ,    $$P\n  $$:      $$.   -    ,d$$'\n  $$;      Y$b._   _,d$P'\n  Y$$.    `.`\"Y$$$$P\"'\n  `$$b      \"-.__\n   `Y$$\n     `Y$$.\n       `$$b.\n         `Y$$b.\n            `\"Y$b._\n                `\"\"\"\n",
  "manjaro": "██████████████████  ████████\n██████████████████  ████████\n██████████████████  ████████\n██████████████████  ████████\n████████            ████████\n████████  ████████  ████████\n████████  ████████  ████████\n████████  ████████  ████████\n████████  ████████  ████████\n████████  ████████  ████████\n████████  ████████  ████████\n████████  ████████  ████████\n████████  ████████  ████████\n████████  ████████  ████████\n",
  "gentoo": "         -/oyddmdhs+:.\n      -odNMMMMMMMMNNmhy+-\n    -yNMMMMMMMMMMMNNNmmdhy+-\n  `omMMMMMMMMMMMMNmdmmmmddhhy/`\n  omMMMMMMMMMMMNhhyyyo hmdddhhhdo`\n.ydMMMMMMMMMMdhs++so/s mdddhhhhdm+`\n oyhdmNMMMMMMMNdyooy dmddddhhhhyhNd.\n  :oyhhdNNMMMMMMMNNNmmdddhhhhhyymMh\n    .:+sydNMMMMMNNNmmmdddhhhhhhmMmy\n       /mMMMMMMNNNmmmdddhhhhhmMNhs:\n    `oNMMMMMMMNNNmmmddddhhdmMNhs+`\n  `sNMMMMMMMMNNNmmmdddddmNMmhs/.`\n /NMMMMMMMMNNNNmmmdddmNMNdso/:`\n+MMMMMMMNNNNNmmmmdmNMNdso/:-\nyMNNNNNNNmmmmmNNMmhs+/-`\n/hMMNNNNNNNNMNdhs++/-`\n`/ohdmmddhys+++/:.`\n  `-//////:--.\n",
  "alpine": "       .hddddddddddddddddddddddh.\n       :dddddddddddddddddddddddddd:\n      /dddddddddddddddddddddddddddd/\n     +dddddddddddddddddddddddddddddd+\n   `sdddddddddddddddddddddddddddddddds`\n  `ydddddddddddd++hdddddddddddddddddddy`\n .hddddddddddd+`  `+ddddh:-sdddddddddddh.\n hdddddddddd+`      `+y:    .sddddddddddh\n ddddddddh+`   `//`   `.`     -sddddddddd\n ddddddh+`   `/hddh/`   `:s-    -sddddddd\n ddddh+`   `/+/dddddh/`   `+s-    -sddddd\n ddd+`   `/o` :dddddddh/`   `oy-    .yddd\n hdddyo+ohddyosdddddddddho+oydddy++ohdddh\n.hdddddddddddddddddddddddddddddddddddddh.\n `yddddddddddddddddddddddddddddddddddy`\n   `sdddddddddddddddddddddddddddddddds`\n     +dddddddddddddddddddddddddddddd+\n      /dddddddddddddddddddddddddddd/\n       :dddddddddddddddddddddddddd:\n        .hddddddddddddddddddddddh.\n",
  "opensuse": "           .;ldkO0000Okdl;.\n        .;d00xl:^''''''^:ok00d;.\n      .d00l'                'o00d.\n    .d0Kd'  Okxol:;,.          :O0d.\n   .OKKKK0kOKKKKKKKKKKOxo:,      lKO.\n  ,0KKKKKKKKKKKKKKK0P^,,,^dx:    ;00.\n .OKKKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.\n :KKKKKKKKKKKKKKK: kKx..dd lKd   'OK:\n dKKKKKKKOx0KKKd ^0KKKO' kKKc   dKd\n dKKKKKKKKKK;.;oOKx,..^..;kKKK0.  dKd\n :KKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:\n  kKKKKKKKKKKKKK0x;,,......,;od  lKk\n  '0KKKKKKKKKKKKKKKKKKKK00KKOo^  c00'\n   'kKKKKOxddxkOO00000Okxoc;''   .dKk'\n     l0Ko.                    .c00l'\n      'l0Kk:.              .;xK0l'\n         'lkK0xl:;,,,,;:ldO0kl'\n             '^:ldxkkkkxdl:^'\n",
  "solus": "            -```````````\n           `-+/------------.`\n        .---:mNo---------------.\n      .-----yMMMy:---------------.\n    `------oMMMMMm/----------------`\n   .------/MMMMMMMN+----------------.\n  .------/NMMMMMMMMm-+/--------------.\n `------/NMMMMMMMMMN-:mh/-------------`\n.-----/NMMMMMMMMMMM:-+MMd//oso/:-----.\n-----/NMMMMMMMMMMMM+--mMMMh::smMmyo:--\n----+NMMMMMMMMMMMMMo--yMMMMNo-:yMMMMd/.\n.--oMMMMMMMMMMMMMMMy--yMMMMMMh:-yMMMy-`\n`-sMMMMMMMMMMMMMMMMh--dMMMMMMMd:/Ny+y.\n`-/+osyhhdmmNNMMMMMm-/MMMMMMMmh+/ohm+\n  .------------:://+-/++++++++oshddys:\n   -hhhhyyyyyyyyyyyhhhhddddhysssso-\n    `:ossssssyysssssssssssssssso:`\n      `:+ssssssssssssssssssss+-\n         `-/+ssssssssssso+/-`\n              `.-----..`\n",
  "slackware": "                  :::::::\n             :::::::::::::::::::\n          ::::::::::::::::::::::::\n        ::::::::cllcccccllllllll::::::\n     :::::::::lc               dc:::::::\n    ::::::::cl   clllccllll    oc:::::::::\n   :::::::::o   lc::::::::co   oc::::::::::\n  :::::::::o    cccclc:::::clcc::::::::::::\n  :::::::::lc        cclccclc:::::::::::::\n :::::::::::::lcclcc          lc:::::::::::\n :::::::::cclcc:::::lccclc     oc::::::::::\n :::::::::o    l::::::::::l    lc::::::::::\n  ::::cll:o     clcllcccll     o::::::::::\n  ::::occ:o                  clc::::::::::\n   ::::ocl:c cslclccclclccclclc::::::::::::\n    :::oclcccccccccccccllllllllllllll::::\n     ::lcc1lcccccccccccccccccccccccco::::\n       ::::::::::::::::::::::::::::::::\n         :::::::::::::::::::::::::::\n            ::::::::::::::::::::::\n                 ::::::::::::\n",
  "artix": "                   '\n                   'o'\n                  'ooo'\n                 'ooxoo'\n                'ooxxxoo'\n               'oookkxxoo'\n              'oiioxkkxxoo'\n             ':;:iiiioxxxoo'\n                `'.;::ioxxoo'\n           '-.      `':;jiooo'\n          'oooio-..     `'i:io'\n         'ooooxxxxoio:,.   `'-;'\n        'ooooxxxxxkkxoooIi:-.  `'\n       'ooooxxxxxkkkkxoiiiiiji'\n      'ooooxxxxxkxxoiiii:'`     .i'\n     'ooooxxxxxoi:::'`       .;ioxo'\n    'ooooxooi::'`         .:iiixkxxo'\n   'ooooi:'`                `'';ioxxo'\n  'i:'`                          '':io'\n'`                                   `'\n",
  "endeavouros": "                     ./o.\n                   ./sssso-\n                 `:osssssss+-\n               `:+sssssssssso/.\n             `-/osssssssssssso/.\n           `-/+sssssssssssssssso+:`\n         `-:/+sssssssssssssssssso+/.\n       `.://ossssssssssssssssssssso++-\n      .://+ssssssssssssssssssssssso++:\n    .:///ossssssssssssssssssssssssso++:\n  `:////ssssssssssssssssssssssssssso+++.\n`-////+ssssssssssssssssssssssssssso++++-\n `..-+oosssssssssssssssssssssssso+++++/`\n   ./++++++++++++++++++++++++++++++/:.\n  `:::::::::::::::::::::::::------``\n",
  "garuda": "                     .%;888:8898898:\n                   x;XxXB%89b8:b8%b88:\n                .8Xxd                8X:.\n              .8Xx;                    8x:.\n            .tt8x          .d            x88;\n         .@8x8;          .db:              xx@;\n       ,tSXX             .bbbbbbbbbbbbbbbbbbbB8x@;\n     .SXxx            bBBBBBBBBBBBBBBBBBBBbSBX8;\n   ,888S                                     pd!\n  8X88/                                       q\n  GBB.\n   x%88        d888@8@X@X@X88X@@XX@@X@8@X.\n     dxXd    dB8b8b8B8B08bB88b998888b88x.\n      dxx8o                      .@@;.\n        dx88                   .t@x.\n          d:SS@8ba89aa67a853Sxxad.\n            .d988999889889899dd.\n",
  "popos": "             /////////////\n          /////////////////////\n       ///////*767////////////////\n     //////7676767676*//////////////\n    /////76767//7676767//////////////\n   /////767676/// *76767///////////////\n  ///////767676/// 76767./// 7676*///////\n /////////767676// 76767/// 767676////////\n///////// 76767676767 //// 76767/////////\n////////// 76767676 ////// 7676//////////\n///////////, 7676 ,/////// 767///////////\n////////////* 7676 /////// 76////////////\n////////////// 7676 ////////////////////\n /////////////// 7676 /// 767////////////\n  ////////////////////// '////////////\n   //////.7676767676767676767,//////\n    ///// 767676767676767676767 /////\n      ///////////////////////////\n         /////////////////////\n             /////////////\n",
  "mint": "             ...-:::::-...\n          .-MMMMMMMMMMMMMMM-.\n       .-MMMM`..-:::::::-..`MMMM-.\n     .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.\n    -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-\n  `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`\n  :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:\n .MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.\n :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:\n :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:\n :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:\n .MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.\n  :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:\n   :MMM:MMM:`                `:MMM:MMM:\n    .MMM.MMMM:--------------:MMMM.MMM.\n      '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'\n        '.-MMMM ``--:::::--`` MMMM-.'\n            '-MMMMMMMMMMMMM-'\n               ``-:::::-``\n",
  "centos": "                 ..\n                .PLTJ.\n               <><><><>\n      KKSSV' 4KKK LJ KKKL.'VSSKK\n      KKV' 4KKKKK LJ KKKKAL 'VKK\n      V' ' 'VKKKK LJ KKKKV' ' 'V\n      .4MA.' 'VKK LJ KKV' '.4Mb.\n   . KKKKKA.' 'V LJ V' '.4KKKKK .\n .4D KKKKKKK.A'' LJ ''.4KKKKKK FA.\n<QDD ++++++++++++  ++++++++++++ GFD>\n 'VD KKKKKKKK'.. LJ ..'KKKKKKKK FV\n   ' VKKKKK'. .4 LJ K. .'KKKKKV '\n      'VK'. .4KK LJ KKA. .'KV'\n      A. . .4KKKK LJ KKKKA. . .4\n      KKA. 'KKKKK LJ KKKKK' .4KK\n      KKSSA. VKKK LJ KKKV .4SSKK\n              <><><><>\n                'MKKM'\n                  ''\n"
}

OS_LOGO_MAP = {
    "arch": "arch", "artix": "artix", "manjaro": "manjaro", "endeavouros": "endeavouros",
    "garuda": "garuda",
    "nixos": "nixos",
    "ubuntu": "ubuntu", "linuxmint": "mint", "pop": "popos", "elementary": "ubuntu",
    "debian": "debian", "raspbian": "debian", "kali": "debian",
    "fedora": "fedora", "rhel": "centos", "centos": "centos", "rocky": "centos",
    "almalinux": "centos", "fedora-asahi-remix": "fedora",
    "void": "void",
    "gentoo": "gentoo",
    "alpine": "alpine",
    "opensuse": "opensuse", "suse": "opensuse",
    "solus": "solus",
    "slackware": "slackware",
    "deepin": "debian",
}

# ═══════════════════════════════════════════════════════════
# Presets de paleta
# ═══════════════════════════════════════════════════════════
PRESETS = {
    "flags": {
        "xenogender":   ["#FF6692", "#FF9A98", "#FFB883", "#FBFFA8", "#85BCFF", "#9D85FF", "#A510FF"],
        "trans":        ["#55CDFC", "#F7A8B8", "#FFFFFF", "#F7A8B8", "#55CDFC"],
        "nb":           ["#FFF430", "#FFFFFF", "#9C59D1", "#2C2C2C"],
        "genderfluid":  ["#FF75A2", "#FFFFFF", "#C011D7", "#2C2C2C", "#3170D0"],
        "pan":          ["#FF218C", "#FFD800", "#21B1FF"],
        "bi":           ["#D60270", "#9B4F96", "#0038A8"],
        "ace":          ["#000000", "#A4A4A4", "#FFFFFF", "#810081"],
        "lesbian":      ["#D52D00", "#FF9A56", "#FFFFFF", "#D362A4", "#A30262"],
        "gay":          ["#078D70", "#26CEAA", "#98E8C1", "#FFFFFF", "#7BADE2", "#5049CC", "#3D1A78"],
        "intersex":     ["#FFD700", "#7902AA"],
        "aromantic":    ["#3DA542", "#A8D47A", "#FFFFFF", "#A8D47A", "#3DA542", "#000000"],
        "agender":      ["#000000", "#BABABA", "#FFFFFF", "#BABABA", "#000000"],
    },
    "themes": {
        "arch":             ["#1793D1", "#1793D1", "#1793D1", "#1793D1", "#1793D1"],
        "catppuccin-mocha": ["#f5c2e7", "#cba6f7", "#94e2d5", "#a6e3a1", "#f9e2af", "#fab387", "#89b4fa"],
        "catppuccin-latte": ["#dd7878", "#8839ef", "#40a02b", "#fe640b", "#df8e1d", "#04a5e5", "#209fb5"],
        "dracula":          ["#ff5555", "#ff79c6", "#bd93f9", "#50fa7b", "#f1fa8c", "#ffb86c", "#8be9fd"],
        "gruvbox":          ["#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#fb4934"],
        "tokyonight":       ["#f7768e", "#bb9af7", "#7dcfff", "#9ece6a", "#e0af68", "#73daca", "#ff9e64"],
        "nord":             ["#bf616a", "#d08770", "#ebcb8b", "#a3be8c", "#b48ead", "#88c0d0", "#81a1c1"],
        "everforest":       ["#e67e80", "#e69875", "#dbbc7f", "#a7c080", "#7fbbb3", "#83c092", "#d3c6aa"],
        "solarized-dark":   ["#dc322f", "#cb4b16", "#b58900", "#859900", "#6c71c4", "#268bd2", "#2aa198"],
        "monokai":          ["#f92672", "#fd971f", "#e6db74", "#a6e22e", "#66d9ef", "#ae81ff", "#f8f8f2"],
        "one-dark":         ["#e06c75", "#d19a66", "#e5c07b", "#98c379", "#56b6c2", "#61afef", "#c678dd"],
        "rose-pine":        ["#eb6f92", "#f6c177", "#ebbcba", "#31748f", "#9ccfd8", "#c4a7e7", "#e0def4"],
        "synthwave":        ["#ff7edb", "#ff7edb", "#36f9f6", "#36f9f6", "#ffe066", "#ffe066", "#b4a0ff"],
    }
}

# ═══════════════════════════════════════════════════════════
# Config padrão
# ═══════════════════════════════════════════════════════════
DEFAULT_CFG = {
    "logo": {
        "path": "~/.config/atlasfetch/logo.txt",
        "colors": ["#FF6692", "#FF9A98", "#FFB883", "#FBFFA8",
                    "#85BCFF", "#9D85FF", "#A510FF"]
    },
    "title": {
        "format": "{user}@{host}",
        "color": "#FF9A98"
    },
    "separator": {
        "char": "\u2500",
        "color": "#9D85FF",
        "length": 48
    },
    "panel": {
        "sep_color": "#9D85FF",
        "val_color": "#f5dce3",
        "left_pad": 3,
        "right_pad": 3,
        "gap": 2,
        "max_shift": 2
    },
    "display": {
        "left": [
            ["os",       "\uf17c", "OS"],
            ["user",     "\uf007", "Usr"],
            ["kernel",   "\ue271", "Krn"],
            ["packages", "\uf1b3", "Pkg"],
            ["shell",    "\uf489", "Sh"],
            ["wm",       "\uf108", "WM"]
        ],
        "right": [
            ["uptime",   "\uf017", "Up"],
            ["terminal", "\uf120", "Term"],
            ["cpu",      "\uf2db", "CPU"],
            ["gpu",      "\uf26c", "GPU"],
            ["memory",   "\uf1c0", "Mem"],
            ["disk",     "\uf0a0", "Dsk"]
        ]
    },
    "palette": {
        "load": "blue",
        "processes": "green"
    },
    "setup_done": False,
    "custom_palettes": {}
}

# ═══════════════════════════════════════════════════════════
# Carga de config + logo
# ═══════════════════════════════════════════════════════════
def _deep_merge(base, patch):
    for k, v in patch.items():
        if isinstance(v, dict) and k in base and isinstance(base[k], dict):
            _deep_merge(base[k], v)
        else:
            base[k] = v

def load_config():
    cfg = json.loads(json.dumps(DEFAULT_CFG))  # deep copy
    path = os.path.expanduser("~/.config/atlasfetch/config.json")
    try:
        with open(path) as f:
            _deep_merge(cfg, json.load(f))
    except (FileNotFoundError, json.JSONDecodeError):
        pass
    return cfg

def load_logo(cfg):
    path = os.path.expanduser(cfg.get("logo", {}).get("path", ""))
    if path:
        try:
            with open(path) as f:
                return f.read()
        except OSError:
            pass
    return ATLAS_LOGO

def write_defaults():
    d = os.path.expanduser("~/.config/atlasfetch")
    os.makedirs(d, exist_ok=True)
    cfg_path = os.path.join(d, "config.json")
    if not os.path.exists(cfg_path):
        with open(cfg_path, "w") as f:
            json.dump(DEFAULT_CFG, f, indent=2)
            f.write("\n")
    logo_path = os.path.join(d, "logo.txt")
    if not os.path.exists(logo_path):
        with open(logo_path, "w") as f:
            f.write(ATLAS_LOGO)

# ═══════════════════════════════════════════════════════════
# Utilitários de cor
# ═══════════════════════════════════════════════════════════
def style(text, fg=None, bg=None, bold=False):
    codes = []
    if bold:
        codes.append("1")
    if fg:
        r, g, b = int(fg[1:3], 16), int(fg[3:5], 16), int(fg[5:7], 16)
        codes.append(f"38;2;{r};{g};{b}")
    if bg:
        r, g, b = int(bg[1:3], 16), int(bg[3:5], 16), int(bg[5:7], 16)
        codes.append(f"48;2;{r};{g};{b}")
    return f"\033[{';'.join(codes)}m{text}\033[0m"

def vlen(s):
    return len(re.sub(r'\033\[[0-9;]*m', '', s))

# ═══════════════════════════════════════════════════════════
# Fontes de informação (zero forks, só Python + /proc + /sys)
# ═══════════════════════════════════════════════════════════

def _read_first(path):
    try:
        with open(path) as f:
            return f.read().strip()
    except OSError:
        return ""

def _detect_distro():
    text = _read_first("/etc/os-release")
    for line in text.splitlines():
        if line.startswith("ID="):
            return line.split("=", 1)[1].strip('"')
    return ""

def _count_packages():
    count = 0
    os_id = _detect_distro()

    try:
        count += len(os.listdir("/var/lib/pacman/local/"))
    except OSError:
        pass

    if os_id in ("debian", "ubuntu", "linuxmint", "pop", "elementary", "raspbian", "kali", "deepin"):
        try:
            with open("/var/lib/dpkg/status") as f:
                count += f.read().count("Status: install ok installed")
        except OSError:
            pass

    if os_id in ("void",):
        try:
            db = "/var/db/xbps"
            if os.path.isdir(db):
                count += len([e for e in os.listdir(db) if e.endswith(".plist") or not e.startswith(".")])
        except OSError:
            pass

    if os_id in ("gentoo",):
        try:
            for cat in os.listdir("/var/db/pkg/"):
                cp = os.path.join("/var/db/pkg", cat)
                if os.path.isdir(cp):
                    count += len(os.listdir(cp))
        except OSError:
            pass

    if os_id in ("slackware",):
        try:
            count += len(os.listdir("/var/log/packages/"))
        except OSError:
            pass

    if os_id in ("alpine",):
        try:
            out = subprocess.run(["apk", "info"], capture_output=True, text=True, timeout=5)
            if out.returncode == 0:
                count += len([l for l in out.stdout.splitlines() if l.strip()])
        except Exception:
            pass

    if os_id in ("fedora", "rhel", "centos", "rocky", "almalinux", "opensuse", "suse", "fedora-asahi-remix"):
        try:
            out = subprocess.run(["rpm", "-qa", "--queryformat", "%{NAME}\n"],
                                 capture_output=True, text=True, timeout=10)
            if out.returncode == 0:
                count += len([l for l in out.stdout.splitlines() if l.strip()])
        except Exception:
            pass

    if os_id in ("nixos",):
        try:
            out = subprocess.run(["nix-env", "-q"], capture_output=True, text=True, timeout=10)
            if out.returncode == 0:
                count += len([l for l in out.stdout.splitlines() if l.strip()])
        except Exception:
            pass

    for fp in ("/var/lib/flatpak", os.path.expanduser("~/.local/share/flatpak")):
        app_dir = os.path.join(fp, "app")
        try:
            count += len([d for d in os.listdir(app_dir) if os.path.isdir(os.path.join(app_dir, d))])
        except OSError:
            pass

    try:
        snap_dir = "/var/lib/snapd/snaps"
        if os.path.isdir(snap_dir):
            count += len([e for e in os.listdir(snap_dir) if e.endswith(".snap")])
    except OSError:
        pass

    return count or "—"


def _collect_info(cfg):
    """Coleta todos os campos definidos no display + título."""
    needed = set()
    needed.add("user")
    needed.add("host")
    for side in ("left", "right"):
        for entry in cfg.get("display", {}).get(side, []):
            if entry:
                needed.add(entry[0])
    # título também pode referenciar campos via format
    fmt = cfg.get("title", {}).get("format", "{user}@{host}")
    for m in re.finditer(r"\{(\w+)\}", fmt):
        needed.add(m.group(1))

    info = {}

    def need(name):
        return name in needed

    # ── user / host ──
    if need("user"):
        info["user"] = os.environ.get("USER") or os.environ.get("USERNAME") or "user"
    if need("host"):
        info["host"] = _read_first("/proc/sys/kernel/hostname") or "localhost"

    # ── os ──
    if need("os"):
        os_name = "—"
        text = _read_first("/etc/os-release")
        for line in text.splitlines():
            if "=" in line:
                k, v = line.split("=", 1)
                v = v.strip('"')
                if k == "PRETTY_NAME":
                    os_name = v
                    break
                elif k == "NAME" and os_name == "—":
                    os_name = v
        info["os"] = os_name

    # ── kernel ──
    if need("kernel"):
        info["kernel"] = os.uname().release

    # ── uptime ──
    if need("uptime"):
        try:
            with open("/proc/uptime") as f:
                sec = float(f.read().split()[0])
            h, m = int(sec // 3600), int((sec % 3600) // 60)
            info["uptime"] = f"{h}h {m}m"
        except Exception:
            info["uptime"] = "—"

    # ── packages (multi-distro) ──
    if need("packages"):
        info["packages"] = _count_packages()

    # ── shell ──
    if need("shell"):
        info["shell"] = os.path.basename(os.environ.get("SHELL", "fish"))

    # ── terminal ──
    if need("terminal"):
        term = os.environ.get("TERMINAL") or os.environ.get("TERM", "")
        term = term.lower()
        if not term or term in ("linux", "vt100"):
            term = "—"
        else:
            term = term.replace("xterm-", "")
        info["terminal"] = term

    # ── cpu ──
    if need("cpu"):
        cpu = "—"
        text = _read_first("/proc/cpuinfo")
        for line in text.splitlines():
            if "model name" in line:
                cpu = line.split(":", 1)[1].strip()
                break
        cpu = re.sub(r'\s*\([^)]*\)|\s*®|\s*™|\s*(Quad|Dual|Six|Eight|Twelve|Sixteen)\s*[- ]?Core|\s*Core\b', '', cpu)
        cpu = re.sub(r'\s+with\s+.*', '', cpu)
        cpu = " ".join(cpu.split())
        info["cpu"] = cpu

    # ── gpu (via /sys/class/drm + pci.ids) ──
    if need("gpu"):
        info["gpu"] = _get_gpu()

    # ── memory ──
    if need("memory"):
        try:
            mem = {}
            for line in _read_first("/proc/meminfo").splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    mem[k.strip()] = v.strip()
            total_kb = int(mem.get("MemTotal", "0").replace(" kB", ""))
            avail_kb = int(mem.get("MemAvailable", "0").replace(" kB", ""))
            used_kb = total_kb - avail_kb
            info["memory"] = f"{used_kb/1024**2:.1f}/{total_kb/1024**2:.1f}G"
        except Exception:
            info["memory"] = "—"

    # ── disk ──
    if need("disk"):
        try:
            u = shutil.disk_usage("/")
            info["disk"] = f"{u.used // 2**30}/{u.total // 2**30}G"
        except Exception:
            info["disk"] = "—"

    # ── wm ──
    if need("wm"):
        wm = os.environ.get("XDG_CURRENT_DESKTOP", "")
        if not wm:
            out = _try_hyprctl()
            if out:
                wm = "Hyprland"
        info["wm"] = wm or "—"

    # ── load ──
    if need("load"):
        try:
            with open("/proc/loadavg") as f:
                parts = f.read().split()
            info["load"] = " ".join(parts[:3])
        except Exception:
            info["load"] = "—"

    # ── processes ──
    if need("processes"):
        try:
            procs = [d for d in os.listdir("/proc") if d.isdigit()]
            info["processes"] = str(len(procs))
        except Exception:
            info["processes"] = "—"

    # ── local_ip ──
    if need("local_ip"):
        ip = "—"
        try:
            text = _read_first("/proc/net/route")
            iface = ""
            for line in text.splitlines()[1:]:
                parts = line.split()
                if parts and parts[1] != "00000000":
                    iface = parts[0]
                    break
            if iface:
                with open(f"/sys/class/net/{iface}/address") as f:
                    mac = f.read().strip()
                ip = _get_ip_from_iface(iface)
            info["local_ip"] = ip or "—"
        except Exception:
            info["local_ip"] = "—"

    # ── resolution (fork opcional — hyprctl) ──
    if need("resolution"):
        info["resolution"] = _try_resolution()

    # ── de ──
    if need("de"):
        info["de"] = os.environ.get("XDG_CURRENT_DESKTOP") or "—"

    # ── font ──
    if need("font"):
        info["font"] = _try_font()

    return info


def _try_hyprctl():
    try:
        import subprocess
        return subprocess.run(["hyprctl", "instances"],
                              capture_output=True, text=True, timeout=3).stdout.strip()
    except Exception:
        return ""

def _try_resolution():
    try:
        import subprocess
        for cmd in (
            ["hyprctl", "monitors"],
            ["wlr-randr"],
            ["xrandr"]
        ):
            try:
                out = subprocess.run(cmd, capture_output=True, text=True, timeout=3).stdout
                if "hyprctl" in " ".join(cmd):
                    m = re.search(r"(\d+x\d+)", out)
                elif "wlr-randr" in " ".join(cmd):
                    m = re.search(r"(\d+x\d+)", out)
                else:
                    m = re.search(r"\*.*?(\d+x\d+)", out)
                if m:
                    return m.group(1)
            except Exception:
                continue
    except Exception:
        pass
    return "—"

def _try_font():
    try:
        import subprocess
        return subprocess.run(
            ["fc-match", "-f", "%{family[0]}", "sans"],
            capture_output=True, text=True, timeout=3
        ).stdout.strip()
    except Exception:
        return "—"

def _get_ip_from_iface(iface):
    try:
        import socket, struct, fcntl
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        return socket.inet_ntoa(
            fcntl.ioctl(s.fileno(), 0xc0206921, struct.pack("256s", iface[:15].encode()))[20:24]
        )
    except Exception:
        return "—"


# ── GPU Provider (zero forks — /sys/class/drm + pci.ids) ──

_VENDOR_NAMES = {
    "0x1002": "AMD", "0x1022": "AMD",
    "0x10de": "NVIDIA",
    "0x8086": "Intel",
    "0x1ae0": "Google",
}

def _get_gpu():
    gpu = "—"
    dev_paths = []
    try:
        for entry in sorted(os.listdir("/sys/class/drm/")):
            if entry.startswith("card") and "-" not in entry:
                p = f"/sys/class/drm/{entry}/device"
                if os.path.exists(f"{p}/vendor"):
                    dev_paths.append(p)
    except OSError:
        return gpu

    for p in dev_paths:
        vendor_id = _read_first(f"{p}/vendor")
        device_id = _read_first(f"{p}/device")
        name = _lookup_pci(vendor_id, device_id)
        if name:
            gpu = name
        else:
            gpu = _VENDOR_NAMES.get(vendor_id, vendor_id)
    return gpu

_PCI_CACHE = None

def _load_pci_ids():
    global _PCI_CACHE
    if _PCI_CACHE is not None:
        return _PCI_CACHE
    _PCI_CACHE = {}
    for path in ("/usr/share/hwdata/pci.ids", "/usr/share/misc/pci.ids",
                 "/usr/share/pci.ids"):
        if not os.path.exists(path):
            continue
        try:
            vendors = {}
            cur_vendor = ""
            with open(path, encoding="latin-1", errors="replace") as f:
                for line in f:
                    if line.startswith("#") or line.strip() == "":
                        continue
                    if not line.startswith("\t"):
                        parts = line.split(None, 1)
                        if len(parts) >= 2:
                            cur_vendor = parts[0].lower()
                            vendors[cur_vendor] = parts[1].strip()
                    elif cur_vendor:
                        parts = line.strip().split(None, 1)
                        if len(parts) >= 2:
                            did = parts[0].lower()
                            key = (cur_vendor, did)
                            _PCI_CACHE[key] = f"{vendors[cur_vendor]} {parts[1].strip()}"
        except Exception:
            continue
    return _PCI_CACHE

def _lookup_pci(vendor_id, device_id):
    db = _load_pci_ids()
    if not db:
        return None
    key = (vendor_id.lower().replace("0x", ""), device_id.lower().replace("0x", ""))
    name = db.get(key, "")
    if not name:
        return None
    name = name.replace("Advanced Micro Devices, Inc. [AMD/ATI] ", "")
    name = name.replace("[AMD/ATI] ", "")
    name = name.replace("NVIDIA Corporation ", "")
    name = name.replace("Intel Corporation ", "")
    name = re.sub(r"\s*\(rev\s*\d+\)", "", name)
    m = re.search(r"\[(.+?)\]", name)
    if m:
        inner = m.group(1)
        if not inner.startswith(("0x", "10", "VGA")):
            name = inner
    name = name.replace("Radeon Vega Series / Radeon Vega Mobile Series", "Radeon Vega 8 Graphics")
    name = re.sub(r'\[[0-9a-fA-F]{4}:[0-9a-fA-F]{4,8}\]', '', name)
    name = " ".join(name.split())
    return name

# ═══════════════════════════════════════════════════════════
# Motor de render
# ═══════════════════════════════════════════════════════════

def build(icon, label, value, fg_color, avail_w, panel_cfg):
    seg = f" {icon} {label} "
    sep = "\ue0b0"
    val_text = f" {value} "

    seg_vis = vlen(seg)
    val_vis = vlen(val_text)
    sep_color = panel_cfg.get("sep_color", "#9D85FF")
    val_color = panel_cfg.get("val_color", "#f5dce3")

    if seg_vis + 1 + val_vis > avail_w:
        need = seg_vis + 1 + 3
        if need > avail_w:
            if seg_vis > avail_w - 3:
                seg = f" {icon} "
            val_text = ""
        else:
            r = avail_w - seg_vis - 2
            if r < 1:
                val_text = ""
            else:
                visible = value[:max(0, r - 2)]
                if len(visible) < len(value):
                    visible = visible[:-1] + "\u2026"
                val_text = " " + visible + " "

    out = style(seg, fg=fg_color)
    out += style(sep, fg=sep_color)
    if val_text.strip():
        out += style(val_text, fg=val_color)
    return out, vlen(out)


def cascade_offset(i, total, max_shift):
    if total <= 1:
        return 0
    mid = (total - 1) / 2
    return round(abs((i / mid) - 1) * max_shift) if mid > 0 else 0


def center_line(line, width):
    s = line.rstrip()
    if not s:
        return " " * width
    pad = width - len(s)
    if pad <= 0:
        return s
    return " " * (pad // 2) + s + " " * (pad - pad // 2)


def render(info, logo_lines, logo_colors, cfg):
    tw = shutil.get_terminal_size().columns

    pan = cfg["panel"]
    GAP = pan.get("gap", 2)
    LEFT_PAD = pan.get("left_pad", 3)
    RIGHT_PAD = pan.get("right_pad", 3)
    MAX_SHIFT = pan.get("max_shift", 2)

    # Esconde ASCII se o terminal for estreito demais pros painéis
    if logo_lines:
        lw_test = max(len(l) for l in logo_lines)
        origin_test = (tw - lw_test) // 2
        if origin_test - LEFT_PAD - GAP < 8 or tw - origin_test - lw_test - GAP - RIGHT_PAD - MAX_SHIFT < 8:
            logo_lines = []

    lh = len(logo_lines)
    lw = max(len(l) for l in logo_lines) if logo_lines else 0

    left_defs = cfg.get("display", {}).get("left", [])
    right_defs = cfg.get("display", {}).get("right", [])
    n = max(len(left_defs), len(right_defs))

    # ── título ──
    fmt = cfg.get("title", {}).get("format", "{user}@{host}")
    title_color = cfg.get("title", {}).get("color") or logo_colors[1] if logo_colors else "#ffffff"
    title_text = fmt.format(**info)
    print()
    print(style(f"  {title_text}", fg=title_color, bold=True))

    # ── separador ──
    sep_cfg = cfg.get("separator", {})
    sep_char = sep_cfg.get("char", "\u2500")
    sep_color = sep_cfg.get("color", "#9D85FF")
    sep_len = min(tw - 4, sep_cfg.get("length", 48))
    print(style(f"  {sep_char * sep_len}", fg=sep_color))

    # ── corpo ──
    if lh == 0:
        # sem ASCII → só painéis
        n_iter = n
        logo_origin = 0
        lw = 0
    else:
        n_iter = lh
        logo_origin = (tw - lw) // 2 if lw < tw else 0

    start_row = max(0, (lh - n) // 2)

    for i in range(n_iter):
        in_range = start_row <= i < start_row + n if lh else True

        if in_range:
            idx = i - start_row if lh else i
            shift = cascade_offset(idx, n, MAX_SHIFT)

            l_def = left_defs[idx] if idx < len(left_defs) else None
            r_def = right_defs[idx] if idx < len(right_defs) else None

            l_val = info.get(l_def[0], "—") if l_def else ""
            r_val = info.get(r_def[0], "—") if r_def else ""

            bg_left = logo_colors[idx % len(logo_colors)]
            bg_right = logo_colors[(idx + 3) % len(logo_colors)]
        else:
            shift = cascade_offset(i - start_row + n // 2, n, MAX_SHIFT)
            l_val = r_val = None
            l_def = r_def = None

        # coloriza a logo
        colored_logo = ""
        if lh:
            for ch in center_line(logo_lines[i], lw):
                if ch != " ":
                    colored_logo += style(ch, logo_colors[i % len(logo_colors)])
                else:
                    colored_logo += " "

        if in_range:
            l_start = LEFT_PAD + shift
            l_avail = max(4, logo_origin - l_start - GAP)
            r_avail = max(4, tw - logo_origin - lw - GAP - RIGHT_PAD - MAX_SHIFT)

            l_text = ""
            if l_def:
                l_text, l_vis = build(l_def[1], l_def[2], l_val, bg_left, l_avail, pan)
            else:
                l_vis = 0

            r_text = ""
            if r_def:
                r_text, r_vis = build(r_def[1], r_def[2], r_val, bg_right, r_avail, pan)
            else:
                r_vis = 0

            l_pad = l_avail - l_vis
            l_blk = " " * l_pad if l_pad > 0 else ""
            row = " " * l_start + l_text + l_blk + " " * GAP + colored_logo
            if r_text.strip():
                r_target = tw - RIGHT_PAD - shift
                gap = r_target - r_vis - vlen(row)
                row += " " * max(0, gap) + r_text
        else:
            row = " " * logo_origin + colored_logo

        # garante que a linha tem exatamente tw colunas
        rv = vlen(row)
        if rv > tw:
            while vlen(row) > tw and row:
                row = row[:-1]
        elif rv < tw:
            row += " " * (tw - rv)

        print(row)

    print()

# ═══════════════════════════════════════════════════════════
# Presets / Setup
# ═══════════════════════════════════════════════════════════

def _flatten_presets():
    items = []
    for cat in ("flags", "themes"):
        for name, colors in PRESETS[cat].items():
            items.append((name, colors))
    return items

def _apply_preset(name):
    for cat in PRESETS.values():
        if name in cat:
            return list(cat[name])
    return None

def _list_presets_cmd():
    print()
    print("  Paletas disponíveis:")
    print()
    print("  \033[1mBandeiras LGBTQ+\033[0m")
    for i, (name, colors) in enumerate(PRESETS["flags"].items(), 1):
        swatch = "".join(style("  ", bg=c) for c in colors)
        print(f"  {i:2d}) {name:15s} {swatch}")
    print()
    print("  \033[1mTemas\033[0m")
    offset = len(PRESETS["flags"])
    for i, (name, colors) in enumerate(PRESETS["themes"].items(), offset + 1):
        swatch = "".join(style("  ", bg=c) for c in colors)
        print(f"  {i:2d}) {name:20s} {swatch}")
    print()

def _save_config(cfg):
    path = os.path.expanduser("~/.config/atlasfetch/config.json")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")

def _run_setup():
    write_defaults()
    cfg = load_config()
    distro_id = _detect_distro()
    distro_name = _read_first("/etc/os-release")
    for line in distro_name.splitlines():
        if line.startswith("PRETTY_NAME="):
            distro_name = line.split("=", 1)[1].strip('"')
            break
    else:
        distro_name = distro_id or "Linux"

    print()
    print(style("  atlasfetch setup", bold=True, fg="#FF9A98"))
    print(f"  Distro detectada: {distro_name}")
    print()

    # ── Escolher paleta ──
    all_presets = _flatten_presets()
    print(style("  ── Paleta de cores ──", fg="#9D85FF"))
    print()
    print("  \033[1mBandeiras LGBTQ+\033[0m")
    for i, (name, _) in enumerate(PRESETS["flags"].items(), 1):
        print(f"   {i:2d}) {name}")
    offset = len(PRESETS["flags"])
    print("  \033[1mTemas\033[0m")
    for i, (name, _) in enumerate(PRESETS["themes"].items(), offset + 1):
        print(f"  {i:2d}) {name}")
    print(f"   c)  Criar paleta customizada")
    print(f"   k)  Manter paleta atual")
    print()

    choice = input("  Escolha (1-{}, c, k): ".format(len(all_presets))).strip().lower()
    print()

    colors = None
    if choice == "c":
        raw = input("  Digite cores hex separadas por espaço (ex: #ff0000 #00ff00 #0000ff): ").strip()
        parts = raw.split()
        valid = [p for p in parts if re.match(r'^#[0-9a-fA-F]{6}$', p)]
        if len(valid) >= 2:
            colors = valid
            custom_name = "_".join(valid[:3])
            if "custom_palettes" not in cfg:
                cfg["custom_palettes"] = {}
            cfg["custom_palettes"][custom_name] = colors
            print(style(f"  ✓ Paleta customizada salva", fg="#50fa7b"))
        else:
            print(style("  ✗ Pelo menos 2 cores hex válidas necessárias", fg="#ff5555"))
            colors = DEFAULT_CFG["logo"]["colors"]
    elif choice == "k":
        colors = cfg.get("logo", {}).get("colors", DEFAULT_CFG["logo"]["colors"])
        print(style("  ✓ Paleta atual mantida", fg="#50fa7b"))
    else:
        try:
            idx = int(choice) - 1
            if 0 <= idx < len(all_presets):
                name, colors = all_presets[idx]
                print(style(f"  ✓ Paleta \"{name}\" selecionada", fg="#50fa7b"))
            else:
                raise ValueError
        except (ValueError, IndexError):
            print(style("  ✗ Opção inválida, usando paleta padrão", fg="#ff5555"))
            colors = DEFAULT_CFG["logo"]["colors"]

    # ── Escolher ASCII ──
    print()
    print(style("  ── ASCII Art ──", fg="#9D85FF"))
    print()
    logo_key = OS_LOGO_MAP.get(distro_id, "")
    logo_choices = sorted(DISTRO_LOGOS.keys())
    distro_logo_name = logo_key if logo_key in DISTRO_LOGOS else "arch"

    print(f"   a)  Usar ASCII da distro ({distro_logo_name}) [padrão]")
    print(f"   b)  Escolher outra ASCII")
    print(f"   k)  Manter ASCII atual")
    print()

    logo_choice = input(f"  Escolha (a, b, k): ").strip().lower()
    print()

    if logo_choice == "b":
        print("  ASCIIs disponíveis:")
        for i, lk in enumerate(logo_choices, 1):
            print(f"  {i:2d}) {lk}")
        print()
        lc = input(f"  Escolha (1-{len(logo_choices)}): ").strip()
        try:
            lidx = int(lc) - 1
            if 0 <= lidx < len(logo_choices):
                logo_key = logo_choices[lidx]
            else:
                raise ValueError
        except ValueError:
            logo_key = distro_logo_name
    elif logo_choice == "k":
        logo_key = None
    else:
        logo_key = distro_logo_name

    # ── Aplicar ──
    cfg["logo"]["colors"] = colors
    cfg["setup_done"] = True
    _save_config(cfg)

    if logo_key and logo_key in DISTRO_LOGOS:
        logo_path = os.path.expanduser(cfg["logo"]["path"])
        os.makedirs(os.path.dirname(logo_path), exist_ok=True)
        with open(logo_path, "w") as f:
            f.write(DISTRO_LOGOS[logo_key])
        print(style(f"  ✓ ASCII \"{logo_key}\" salva em {logo_path}", fg="#50fa7b"))

    print()
    print(style("  ✓ Configuração concluída! Execute atlasfetch para ver o resultado.", fg="#50fa7b", bold=True))
    print()

def _show_help():
    print("atlasfetch — fetch customizável com ASCII e powerline")
    print()
    print("Uso:  atlasfetch [opções]")
    print()
    print("Opções:")
    print("  -h, --help            Mostra esta ajuda")
    print("  -v, --version         Mostra a versão")
    print("  -i, --setup           Assistente de configuração interativo")
    print("  --preset <nome>       Aplica uma paleta e sai")
    print("  --list-presets        Lista paletas disponíveis")
    print()
    print("Config:  ~/.config/atlasfetch/config.json")
    print("Logo:    ~/.config/atlasfetch/logo.txt")
    print()
    print("Campos disponíveis para o display:")
    for name in sorted(PROVIDER_DOCS.keys()):
        print(f"  {name:12s} — {PROVIDER_DOCS[name]}")

def main():
    args = sys.argv[1:]

    if "-h" in args or "--help" in args:
        _show_help()
        return

    if "-v" in args or "--version" in args:
        print("atlasfetch 2.0")
        return

    if "--list-presets" in args:
        _list_presets_cmd()
        return

    if "-i" in args or "--setup" in args:
        _run_setup()
        return

    for i, a in enumerate(args):
        if a == "--preset" and i + 1 < len(args):
            name = args[i + 1]
            colors = _apply_preset(name)
            if colors is None:
                cfg_tmp = load_config()
                custom = cfg_tmp.get("custom_palettes", {})
                if name in custom:
                    colors = custom[name]
            if colors:
                write_defaults()
                cfg_tmp = load_config()
                cfg_tmp["logo"]["colors"] = list(colors)
                cfg_tmp["setup_done"] = True
                _save_config(cfg_tmp)
                print(f"Paleta \"{name}\" aplicada.")
            else:
                print(f"Paleta \"{name}\" não encontrada. Use --list-presets.")
            return

    write_defaults()
    global cfg
    cfg = load_config()

    if cfg.get("setup_done") is not True:
        _run_setup()
        cfg = load_config()

    logo_text = load_logo(cfg)
    logo_lines = logo_text.strip("\n").split("\n") if logo_text else []
    logo_colors = cfg.get("logo", {}).get("colors", DEFAULT_CFG["logo"]["colors"])

    info = _collect_info(cfg)
    render(info, logo_lines, logo_colors, cfg)


PROVIDER_DOCS = {
    "os": "Sistema operacional",
    "user": "Nome do usuário",
    "host": "Hostname",
    "kernel": "Versão do kernel",
    "uptime": "Tempo ligado",
    "packages": "Pacotes instalados",
    "shell": "Shell atual",
    "terminal": "Emulador de terminal",
    "cpu": "Modelo da CPU",
    "gpu": "GPU (via /sys + pci.ids)",
    "memory": "RAM usada/total",
    "disk": "Disco usado/total",
    "wm": "Window manager",
    "load": "Load average",
    "processes": "Processos ativos",
    "local_ip": "IP local",
    "resolution": "Resolução do monitor",
    "de": "Desktop environment",
    "font": "Fonte do sistema",
}

cfg = DEFAULT_CFG  # será sobrescrita pelo load_config()

if __name__ == "__main__":
    main()
